sqlite3:
  :adapter: sqlite3
  :database: vendor/plugins/username_suggester/spec/db/username_suggester.sqlite3.db

# mysql:
#   :adapter: mysql
#   :database: username_suggester_test
#   :username: root
#   :password:
#   :host: localhost